version: "3.4"
services:
  client-mysql:
    image: mysql:latest
    container_name: client-mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "client"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    volumes:
      - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"
  client-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: client-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"